[2024-06-30 18:35:01,810] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_datalake_dag.create_datalake_table scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30 18:35:01,823] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_datalake_dag.create_datalake_table scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30 18:35:01,823] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 18:35:01,824] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-30 18:35:01,824] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-30 18:35:01,844] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_datalake_table> on 2024-06-29 00:00:00+00:00
[2024-06-30 18:35:01,870] {standard_task_runner.py:52} INFO - Started process 501 to run task
[2024-06-30 18:35:01,878] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_datalake_dag', 'create_datalake_table', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpth0s6axr', '--error-file', '/tmp/tmp8f9mgnzc']
[2024-06-30 18:35:01,879] {standard_task_runner.py:80} INFO - Job 2: Subtask create_datalake_table
[2024-06-30 18:35:02,048] {task_command.py:371} INFO - Running <TaskInstance: example_datalake_dag.create_datalake_table scheduled__2024-06-29T00:00:00+00:00 [running]> on host 12d6cc628018
[2024-06-30 18:35:02,146] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_datalake_dag
AIRFLOW_CTX_TASK_ID=create_datalake_table
AIRFLOW_CTX_EXECUTION_DATE=2024-06-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-29T00:00:00+00:00
[2024-06-30 18:35:02,184] {base.py:68} INFO - Using connection ID 'datalake_postgres' for task execution.
[2024-06-30 18:35:02,197] {dbapi.py:231} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS datalake_table (
            id SERIAL PRIMARY KEY,
            data VARCHAR(50)
        );
        , parameters: None
[2024-06-30 18:35:02,216] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(datalake_table_id_seq, 2200) already exists.

[2024-06-30 18:35:02,226] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=example_datalake_dag, task_id=create_datalake_table, execution_date=20240629T000000, start_date=20240630T183501, end_date=20240630T183502
[2024-06-30 18:35:02,233] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task create_datalake_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(datalake_table_id_seq, 2200) already exists.
; 501)
[2024-06-30 18:35:02,253] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-06-30 18:35:02,332] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
